import "@/src/app/styles/globals.css"
import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google"
import { BlitzProvider } from "./blitz-client"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: { title: "New Blitz App", template: "%s – Blitz" },
  description: "Generated by blitz new ",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <BlitzProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </BlitzProvider>
      </body>
    </html>
  )
}
